events {}

http {
  client_max_body_size 50M;

  types {
    text/html                             html htm shtml;
    text/css                              css;
    text/xml                              xml;
    image/gif                             gif;
    image/jpeg                            jpeg jpg;
    image/png                             png;
    image/svg+xml                         svg svgz;
    image/webp                            webp;
    image/x-icon                          ico;
    application/javascript                js;
    application/json                      json;
    application/wasm                      wasm;
    font/woff                             woff;
    font/woff2                            woff2;
  }

  default_type application/octet-stream;

  server {
    listen 80;

    # -------- AUTH --------
    location /api/auth/ {
      proxy_pass https://aura-auth.onrender.com;
      proxy_set_header Host aura-auth.onrender.com;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_ssl_server_name on;
    }

    # -------- MUSIC --------
    location /api/music/ {
      proxy_pass https://aura-music-v56h.onrender.com;
      proxy_set_header Host aura-music-v56h.onrender.com;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_ssl_server_name on;
    }

    # -------- NOTIFICATION --------
    location /api/notification/ {
      proxy_pass https://aura-notification.onrender.com;
      proxy_set_header Host aura-notification.onrender.com;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_ssl_server_name on;
    }
  }
}
